/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  publicDocSidebar: [{ type: "autogenerated", dirName: "public-networks" }],
  privateDocSidebar: [{ type: "autogenerated", dirName: "private-networks" }],
  pluginsDocSidebar: [{ type: "autogenerated", dirName: "plugins" }],
};

module.exports = sidebars;
