default: true
no-trailing-punctuation:
  punctuation: '.,;:!'
ul-indent:
  indent: 4

no-bare-urls: false
code-block-style: false
line-length: false

  # excluded rule for as kramdown has a bug.
  # see https://github.com/markdownlint/markdownlint/issues/294#issuecomment-600600407
  # these are now in info style.
  # to be put back in error style once bug fixed.
single-h1: false
no-space-in-code: false
no-duplicate-header: false
first-line-h1: false

  # Because I hate HTML but sometimes a table is hard to format in MD
  # now in info style.
no-inline-html: false

