---
##########################
## OpenAPI Linter rules ##
##########################

extends:
  - spectral:oas

#rules:
#  operation-tag-defined: off
#  operation-operationId: off
#  operation-description: off
#  operation-tags: off
#  oas2-valid-schema-example: off
#  oas2-api-host: off
#  oas2-operation-security-defined: off
#  oas2-api-schemes: off
#  info-contact : off


