name: Build

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: ConsenSys/github-actions/docs-build@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

