# SPDX-License-Identifier: Apache-2.0
---
name: Build without insider

on: [pull_request]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Run build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        shell: sh
        run: pip install -q -r CI/requirements-mkdocs-material.txt -r CI/requirements.txt

      - name: MkDocs Material non insider build
        shell: sh
        run: mkdocs build -s

      - name: Site artifacts
        uses: actions/upload-artifact@v3
        with:
          name: site-no-insider
          path: site
