---
name: Check for link errors

on:
  workflow_call:

jobs:
  linkCheck:
    name: Link Checking
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file-extensions: [".md", ".mdx"]
    steps:
      - uses: actions/checkout@v4
      - name: LinkCheck
        uses: ConsenSys/docs-gha/linkcheck@main
        with:
          FILE_EXTENSION: ${{ matrix.file-extensions }}