# SPDX-License-Identifier: Apache-2.0
---
name: Nightly check

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  "0 0 * * *"
  workflow_dispatch: {}

concurrency:
  group: nightly-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Run check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v3

      - name: Test all the links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: yes
          use-verbose-mode: yes
          check-modified-files-only: no
          base-branch: main
          config-file: ./CI/linkchecker/link_check_conf.json
