name: Publish main branch docs to GitHub Pages
# NOTE that we publish `main` to github pages branch: gh-pages
# and previews only are handled by vercel

on:
  push:
    branches: main

jobs:
  publish-docs-to-gh-pages:
    name: Publish docs to `./` directory of `gh-pages` branch
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install npm dependencies
        run: yarn --immutable

      - name: Run build script
        run: yarn build
        
      - name: Deploy to `./` directory of `gh-pages` branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          keep_files: true
