name: Publish main branch docs to GitHub Pages
# NOTE that we publish `main` to github pages branch: gh-pages
# and previews only are handled by vercel

on:
  push:
    branches: main

jobs:
  publish-docs-to-gh-pages:
    name: Publish docs to `./` directory of `gh-pages` branch
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
          node-version-file: '.nvmrc'

      - name: npm build
        shell: bash
        run: |
          npm ci --only=production
          npm run build 
        
      - name: Deploy to `./` directory of `gh-pages` branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          keep_files: true
