name: Publish docs to GitHub Pages

on:
  workflow_call:
    inputs:
      destination_dir:
        type: string
      ref:
        required: false
        type: string

jobs:
  publish-docs-to-gh-pages:
    name: Publish docs to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install npm dependencies
        run: yarn --immutable
      - name: Run build script
        run: DEST="/${{ inputs.destination_dir }}" yarn build
      - name: Deploy to `${{ inputs.destination_dir }}` directory of `gh-pages` branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          destination_dir: ${{ inputs.destination_dir }}
          keep_files: true

