# SPDX-License-Identifier: Apache-2.0
---
name: Weekly check

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  "0 0 * * 0"
  workflow_dispatch: {}

concurrency:
  group: weekly-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Run check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint repository
        uses: philips-labs/github-action-repolinter@2d7dc7e43a8d8d52db80b010434df2b8388b5817
        env:
          CUSTOM_REPOLINT_FILE: https://github.com/hyperledger-labs/hyperledger-community-management-tools/raw/main/repo_structure/repolint.json
